### ISSUE TITLE
Add test of package loading

### ISSUE THREAD

**Issue by alex-konovalov** [gap-infra/gap-docker-master-testsuite#1]

**Comment by alex-konovalov** [comment]
See https://github.com/gap-system/gap-docker-stable-4.9-testsuite/pull/1 - will be propagated to other repos once merged.

**Comment by alex-konovalov** [comment]
Closed in https://github.com/gap-infra/gap-docker-master-testsuite/pull/3

**Comment by fingolfin** [comment]
@alex-konovalov you wrote this was "closed in #3", yet the issue remains open. Intentional, or should this be closed now?
